// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8i1f8dJ8EWChjQCB5eXvuxYMF4Mfqu6Y',
    appId: '1:739892742913:web:283a74d8ff247baa1de900',
    messagingSenderId: '739892742913',
    projectId: 'fir-824f5',
    authDomain: 'fir-824f5.firebaseapp.com',
    storageBucket: 'fir-824f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS-5PmtGXUkxSPOW0wdAHRJj8UTElMg9U',
    appId: '1:739892742913:android:24b2600e85596d1d1de900',
    messagingSenderId: '739892742913',
    projectId: 'fir-824f5',
    storageBucket: 'fir-824f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUIj5pBGU33Pq-We48SfU_S0xEBQOSyQ',
    appId: '1:739892742913:ios:ca2ad3a19cddfc8b1de900',
    messagingSenderId: '739892742913',
    projectId: 'fir-824f5',
    storageBucket: 'fir-824f5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUIj5pBGU33Pq-We48SfU_S0xEBQOSyQ',
    appId: '1:739892742913:ios:ca2ad3a19cddfc8b1de900',
    messagingSenderId: '739892742913',
    projectId: 'fir-824f5',
    storageBucket: 'fir-824f5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8i1f8dJ8EWChjQCB5eXvuxYMF4Mfqu6Y',
    appId: '1:739892742913:web:1a8109c167b0926e1de900',
    messagingSenderId: '739892742913',
    projectId: 'fir-824f5',
    authDomain: 'fir-824f5.firebaseapp.com',
    storageBucket: 'fir-824f5.firebasestorage.app',
  );
}
